# Generated by Django 6.0 on 2025-12-30 10:02

import common.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('churches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GivingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_tax_deductible', models.BooleanField(default=True, verbose_name='Tax Deductible')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('has_target', models.BooleanField(default=False, verbose_name='Has Target')),
                ('monthly_target', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monthly Target')),
                ('yearly_target', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Yearly Target')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giving_categories', to='churches.church')),
            ],
            options={
                'verbose_name': 'Giving Category',
                'verbose_name_plural': 'Giving Categories',
                'db_table': 'giving_categories',
                'ordering': ['church', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GivingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Campaign Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[common.validators.validate_amount], verbose_name='Target Amount')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Current Amount')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='campaign_images/', verbose_name='Featured Image')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL')),
                ('terms_and_conditions', models.TextField(blank=True, verbose_name='Terms and Conditions')),
                ('allow_anonymous', models.BooleanField(default=True, verbose_name='Allow Anonymous Giving')),
                ('show_publicly', models.BooleanField(default=True, verbose_name='Show Publicly')),
                ('enable_updates', models.BooleanField(default=True, verbose_name='Enable Updates')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giving_campaigns', to='churches.church')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='giving.givingcategory')),
            ],
            options={
                'verbose_name': 'Giving Campaign',
                'verbose_name_plural': 'Giving Campaigns',
                'db_table': 'giving_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GivingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Transaction ID')),
                ('transaction_type', models.CharField(choices=[('one_time', 'One-Time'), ('recurring', 'Recurring'), ('pledge_payment', 'Pledge Payment'), ('special_offering', 'Special Offering'), ('mission_trip', 'Mission Trip'), ('building_fund', 'Building Fund'), ('other', 'Other')], default='one_time', max_length=20, verbose_name='Transaction Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[common.validators.validate_amount], verbose_name='Amount')),
                ('currency', models.CharField(default='KES', max_length=3, verbose_name='Currency')),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('check', 'Check'), ('mobile_money', 'Mobile Money'), ('card', 'Card'), ('other', 'Other')], default='mpesa', max_length=20, verbose_name='Payment Method')),
                ('payment_reference', models.CharField(blank=True, help_text='M-Pesa transaction ID, bank reference, etc.', max_length=100, verbose_name='Payment Reference')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('transaction_date', models.DateTimeField(verbose_name='Transaction Date')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Completed Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Anonymous')),
                ('dedication', models.CharField(blank=True, max_length=500, verbose_name='Dedication')),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Refund Amount')),
                ('refund_reason', models.TextField(blank=True, verbose_name='Refund Reason')),
                ('refund_date', models.DateTimeField(blank=True, null=True, verbose_name='Refund Date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='giving_transactions', to='giving.givingcategory')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='giving_transactions', to='churches.church')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='giving_transactions', to='accounts.member')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Giving Transaction',
                'verbose_name_plural': 'Giving Transactions',
                'db_table': 'giving_transactions',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='GivingTransactionCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Allocated Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='giving.givingcampaign')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='giving.givingtransaction')),
            ],
            options={
                'verbose_name': 'Transaction Campaign',
                'verbose_name_plural': 'Transaction Campaigns',
                'db_table': 'giving_transaction_campaigns',
            },
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pledge_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[common.validators.validate_amount], verbose_name='Pledge Amount')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Paid Amount')),
                ('pledge_date', models.DateField(verbose_name='Pledge Date')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('partially_paid', 'Partially Paid'), ('fully_paid', 'Fully Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='active', max_length=20, verbose_name='Status')),
                ('title', models.CharField(max_length=200, verbose_name='Pledge Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('payment_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('bi_weekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20, verbose_name='Payment Frequency')),
                ('installment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Installment Amount')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pledges', to='giving.givingcategory')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='churches.church')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='accounts.member')),
            ],
            options={
                'verbose_name': 'Pledge',
                'verbose_name_plural': 'Pledges',
                'db_table': 'giving_pledges',
                'ordering': ['-pledge_date'],
            },
        ),
        migrations.AddField(
            model_name='givingtransaction',
            name='pledge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='giving.pledge'),
        ),
        migrations.CreateModel(
            name='RecurringGiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('bi_weekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20, verbose_name='Frequency')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[common.validators.validate_amount], verbose_name='Amount')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('next_payment_date', models.DateField(verbose_name='Next Payment Date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='active', max_length=20, verbose_name='Status')),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('check', 'Check'), ('mobile_money', 'Mobile Money'), ('card', 'Card'), ('other', 'Other')], default='mpesa', max_length=20, verbose_name='Payment Method')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('total_amount_given', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Amount Given')),
                ('total_transactions', models.PositiveIntegerField(default=0, verbose_name='Total Transactions')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_giving', to='giving.givingcategory')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_giving', to='churches.church')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_giving', to='accounts.member')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recurring Giving',
                'verbose_name_plural': 'Recurring Giving',
                'db_table': 'giving_recurring',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='givingtransaction',
            name='recurring_giving',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='giving.recurringgiving'),
        ),
        migrations.AddIndex(
            model_name='givingcategory',
            index=models.Index(fields=['church'], name='giving_cate_church__3a5338_idx'),
        ),
        migrations.AddIndex(
            model_name='givingcategory',
            index=models.Index(fields=['is_active'], name='giving_cate_is_acti_671a47_idx'),
        ),
        migrations.AddIndex(
            model_name='givingcategory',
            index=models.Index(fields=['display_order'], name='giving_cate_display_8c9716_idx'),
        ),
        migrations.AddIndex(
            model_name='givingcampaign',
            index=models.Index(fields=['church'], name='giving_camp_church__5c7148_idx'),
        ),
        migrations.AddIndex(
            model_name='givingcampaign',
            index=models.Index(fields=['category'], name='giving_camp_categor_71d56a_idx'),
        ),
        migrations.AddIndex(
            model_name='givingcampaign',
            index=models.Index(fields=['status'], name='giving_camp_status_e7ba24_idx'),
        ),
        migrations.AddIndex(
            model_name='givingcampaign',
            index=models.Index(fields=['start_date'], name='giving_camp_start_d_d82506_idx'),
        ),
        migrations.AddIndex(
            model_name='givingcampaign',
            index=models.Index(fields=['end_date'], name='giving_camp_end_dat_840ca8_idx'),
        ),
        migrations.AddIndex(
            model_name='givingtransactioncampaign',
            index=models.Index(fields=['transaction'], name='giving_tran_transac_b23e15_idx'),
        ),
        migrations.AddIndex(
            model_name='givingtransactioncampaign',
            index=models.Index(fields=['campaign'], name='giving_tran_campaig_fcbb5f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='givingtransactioncampaign',
            unique_together={('transaction', 'campaign')},
        ),
        migrations.AddIndex(
            model_name='pledge',
            index=models.Index(fields=['member'], name='giving_pled_member__0292ae_idx'),
        ),
        migrations.AddIndex(
            model_name='pledge',
            index=models.Index(fields=['church'], name='giving_pled_church__c4fdd1_idx'),
        ),
        migrations.AddIndex(
            model_name='pledge',
            index=models.Index(fields=['category'], name='giving_pled_categor_562695_idx'),
        ),
        migrations.AddIndex(
            model_name='pledge',
            index=models.Index(fields=['status'], name='giving_pled_status_820a2c_idx'),
        ),
        migrations.AddIndex(
            model_name='pledge',
            index=models.Index(fields=['pledge_date'], name='giving_pled_pledge__5bdcc0_idx'),
        ),
        migrations.AddIndex(
            model_name='pledge',
            index=models.Index(fields=['end_date'], name='giving_pled_end_dat_4c9fa8_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringgiving',
            index=models.Index(fields=['member'], name='giving_recu_member__5ac644_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringgiving',
            index=models.Index(fields=['church'], name='giving_recu_church__31c2f6_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringgiving',
            index=models.Index(fields=['category'], name='giving_recu_categor_1f2607_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringgiving',
            index=models.Index(fields=['status'], name='giving_recu_status_1cf693_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringgiving',
            index=models.Index(fields=['frequency'], name='giving_recu_frequen_04b07b_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringgiving',
            index=models.Index(fields=['next_payment_date'], name='giving_recu_next_pa_54323f_idx'),
        ),
        migrations.AddIndex(
            model_name='givingtransaction',
            index=models.Index(fields=['transaction_id'], name='giving_tran_transac_6cf3af_idx'),
        ),
        migrations.AddIndex(
            model_name='givingtransaction',
            index=models.Index(fields=['member'], name='giving_tran_member__069a39_idx'),
        ),
        migrations.AddIndex(
            model_name='givingtransaction',
            index=models.Index(fields=['church'], name='giving_tran_church__6a9ad1_idx'),
        ),
        migrations.AddIndex(
            model_name='givingtransaction',
            index=models.Index(fields=['category'], name='giving_tran_categor_e4a185_idx'),
        ),
        migrations.AddIndex(
            model_name='givingtransaction',
            index=models.Index(fields=['status'], name='giving_tran_status_3211ac_idx'),
        ),
        migrations.AddIndex(
            model_name='givingtransaction',
            index=models.Index(fields=['transaction_type'], name='giving_tran_transac_190d89_idx'),
        ),
        migrations.AddIndex(
            model_name='givingtransaction',
            index=models.Index(fields=['payment_method'], name='giving_tran_payment_7eb24f_idx'),
        ),
        migrations.AddIndex(
            model_name='givingtransaction',
            index=models.Index(fields=['transaction_date'], name='giving_tran_transac_187deb_idx'),
        ),
        migrations.AddIndex(
            model_name='givingtransaction',
            index=models.Index(fields=['payment_reference'], name='giving_tran_payment_4c8d66_idx'),
        ),
    ]
