# Generated by Django 6.0.1 on 2026-01-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giving', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='givingcampaign',
            name='featured_image',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Featured Image URL'),
        ),
    ]
