# Generated by Django 6.0.1 on 2026-02-27 11:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0004_church_accent_color_church_bank_account_name_and_more'),
        ('giving', '0002_alter_givingcampaign_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='givingtransaction',
            name='disbursement_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Disbursement Status'),
        ),
        migrations.CreateModel(
            name='ChurchDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Disbursement Amount')),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Platform Fee')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Net Amount')),
                ('disbursement_method', models.CharField(choices=[('paystack', 'Paystack'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], default='paystack', max_length=20, verbose_name='Disbursement Method')),
                ('conversation_id', models.CharField(blank=True, help_text='Paystack transfer ID', max_length=100, null=True, verbose_name='Transfer ID')),
                ('transfer_code', models.CharField(blank=True, help_text='Paystack transfer code', max_length=100, null=True, verbose_name='Transfer Code')),
                ('paystack_receipt', models.CharField(blank=True, help_text='Paystack transfer reference', max_length=50, null=True, verbose_name='Paystack Receipt')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('pending_retry', 'Pending Retry')], default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Retry Count')),
                ('max_retries', models.PositiveIntegerField(default=3, verbose_name='Max Retries')),
                ('next_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='Next Retry At')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='churches.church')),
                ('giving_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disbursement', to='giving.givingtransaction')),
            ],
            options={
                'verbose_name': 'Church Disbursement',
                'verbose_name_plural': 'Church Disbursements',
                'db_table': 'church_disbursements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['giving_transaction'], name='church_disb_giving__cd17ee_idx'), models.Index(fields=['church'], name='church_disb_church__4bbd15_idx'), models.Index(fields=['status'], name='church_disb_status_3ff8c4_idx'), models.Index(fields=['disbursement_method'], name='church_disb_disburs_6551e9_idx'), models.Index(fields=['conversation_id'], name='church_disb_convers_f6120b_idx'), models.Index(fields=['transfer_code'], name='church_disb_transfe_c2b931_idx'), models.Index(fields=['next_retry_at'], name='church_disb_next_re_ccb2c5_idx')],
            },
        ),
    ]
