# Generated by Django 6.0 on 2025-12-31 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('registration_certificate', 'Registration Certificate'), ('tax_exemption', 'Tax Exemption Certificate'), ('constitution', 'Church Constitution'), ('bylaws', 'Bylaws'), ('board_resolution', 'Board Resolution'), ('pastor_appointment', 'Pastor Appointment Letter'), ('bank_account', 'Bank Account Verification'), ('other', 'Other Document')], max_length=30, verbose_name='Document Type')),
                ('title', models.CharField(max_length=200, verbose_name='Document Title')),
                ('file', models.FileField(max_length=255, upload_to='church_documents/%Y/%m/', verbose_name='Document File')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('verification_notes', models.TextField(blank=True, verbose_name='Verification Notes')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='churches.church')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Church Document',
                'verbose_name_plural': 'Church Documents',
                'db_table': 'church_documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['church', 'document_type'], name='church_docu_church__9ad9d3_idx'), models.Index(fields=['is_verified'], name='church_docu_is_veri_12b11c_idx')],
                'unique_together': {('church', 'document_type')},
            },
        ),
    ]
