# Generated by Django 6.0.1 on 2026-02-27 11:04

import common.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0003_church_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='accent_color',
            field=models.CharField(default='#F59E0B', help_text='Hex color code (e.g., #F59E0B)', max_length=7, verbose_name='Accent Color'),
        ),
        migrations.AddField(
            model_name='church',
            name='bank_account_name',
            field=models.CharField(blank=True, help_text='Bank account name for donations', max_length=200, verbose_name='Bank Account Name'),
        ),
        migrations.AddField(
            model_name='church',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Bank account number for donations', max_length=50, validators=[common.validators.validate_bank_account_number], verbose_name='Bank Account Number'),
        ),
        migrations.AddField(
            model_name='church',
            name='bank_branch',
            field=models.CharField(blank=True, help_text='Bank branch for donations', max_length=100, verbose_name='Bank Branch'),
        ),
        migrations.AddField(
            model_name='church',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name for donations', max_length=100, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='church',
            name='enable_paystack',
            field=models.BooleanField(default=False, verbose_name='Enable Paystack'),
        ),
        migrations.AddField(
            model_name='church',
            name='logo',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Church Logo'),
        ),
        migrations.AddField(
            model_name='church',
            name='mpesa_account_number',
            field=models.CharField(blank=True, help_text='M-Pesa account number (usually church code or name)', max_length=50, verbose_name='M-Pesa Account Number'),
        ),
        migrations.AddField(
            model_name='church',
            name='mpesa_paybill_number',
            field=models.CharField(blank=True, help_text='M-Pesa Paybill number for donations', max_length=10, validators=[common.validators.validate_paybill_number], verbose_name='M-Pesa Paybill Number'),
        ),
        migrations.AddField(
            model_name='church',
            name='mpesa_till_number',
            field=models.CharField(blank=True, help_text='M-Pesa Till number for donations (alternative to Paybill)', max_length=10, validators=[common.validators.validate_till_number], verbose_name='M-Pesa Till Number'),
        ),
        migrations.AddField(
            model_name='church',
            name='paystack_public_key',
            field=models.CharField(blank=True, help_text='Paystack public key for online payments', max_length=200, verbose_name='Paystack Public Key'),
        ),
        migrations.AddField(
            model_name='church',
            name='paystack_secret_key',
            field=models.CharField(blank=True, help_text='Paystack secret key for online payments', max_length=200, verbose_name='Paystack Secret Key'),
        ),
        migrations.AddField(
            model_name='church',
            name='primary_color',
            field=models.CharField(default='#3B82F6', help_text='Hex color code (e.g., #3B82F6)', max_length=7, verbose_name='Primary Theme Color'),
        ),
        migrations.AddField(
            model_name='church',
            name='secondary_color',
            field=models.CharField(default='#10B981', help_text='Hex color code (e.g., #10B981)', max_length=7, verbose_name='Secondary Theme Color'),
        ),
        migrations.CreateModel(
            name='ChurchService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('service_type', models.CharField(choices=[('sunday_morning', 'Sunday Morning Service'), ('sunday_evening', 'Sunday Evening Service'), ('midweek', 'Midweek Service'), ('prayer', 'Prayer Meeting'), ('youth', 'Youth Service'), ('children', 'Children Service'), ('special', 'Special Service'), ('other', 'Other')], default='sunday_morning', max_length=20, verbose_name='Service Type')),
                ('name', models.CharField(max_length=200, verbose_name='Service Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('day_of_week', models.CharField(blank=True, max_length=20, verbose_name='Day of Week')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('is_recurring', models.BooleanField(default=True, verbose_name='Recurring Service')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('pastor_name', models.CharField(blank=True, max_length=200, verbose_name='Pastor Name')),
                ('speaker_name', models.CharField(blank=True, max_length=200, verbose_name='Speaker Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('requires_registration', models.BooleanField(default=False, verbose_name='Requires Registration')),
                ('max_attendees', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum Attendees')),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='churches.campus')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='churches.church')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Church Service',
                'verbose_name_plural': 'Church Services',
                'db_table': 'churches_services',
                'ordering': ['church', 'day_of_week', 'start_time'],
                'indexes': [models.Index(fields=['church'], name='churches_se_church__237c35_idx'), models.Index(fields=['campus'], name='churches_se_campus__334e82_idx'), models.Index(fields=['service_type'], name='churches_se_service_403a3a_idx'), models.Index(fields=['day_of_week'], name='churches_se_day_of__78e644_idx'), models.Index(fields=['is_active'], name='churches_se_is_acti_d7a101_idx')],
            },
        ),
    ]
