# Generated by Django 6.0 on 2025-12-30 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('churches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_church_admin',
            new_name='is_email_verified',
        ),
        migrations.RemoveField(
            model_name='member',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='member',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='member',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='member',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='members', to='churches.department'),
        ),
        migrations.AddField(
            model_name='member',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='employer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='id_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='is_tithe_payer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='kra_pin',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_status',
            field=models.CharField(choices=[('visitor', 'Visitor'), ('new_member', 'New Member'), ('member', 'Member'), ('inactive', 'Inactive')], default='new_member', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='monthly_giving_goal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='preferred_giving_method',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='small_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='churches.smallgroup'),
        ),
        migrations.AddField(
            model_name='member',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='churches.church'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_device',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='user',
            name='push_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('pastor', 'Pastor'), ('treasurer', 'Treasurer'), ('auditor', 'Auditor'), ('denomination_admin', 'Denomination Admin'), ('system_admin', 'System Admin')], default='member', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersession',
            name='device_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
