# Generated by Django 6.0 on 2025-12-30 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_is_church_admin_user_is_email_verified_and_more'),
        ('churches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='churches.church'),
        ),
    ]
