# Generated by Django 6.0.1 on 2026-02-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('admin', 'Admin'), ('pastor', 'Pastor'), ('treasurer', 'Treasurer'), ('auditor', 'Auditor'), ('denomination_admin', 'Denomination Admin'), ('system_admin', 'System Admin')], default='member', max_length=20),
        ),
    ]
