# Generated by Django 6.0.1 on 2026-02-06 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_role'),
        ('churches', '0003_church_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_code', models.CharField(max_length=50, verbose_name='Church Code Used')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message from Applicant')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Rejection Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='churches.church', verbose_name='Church')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_join_requests', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_join_requests', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Church Join Request',
                'verbose_name_plural': 'Church Join Requests',
                'db_table': 'church_join_requests',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'church', 'status')},
            },
        ),
    ]
