# Generated by Django 6.0.1 on 2026-02-04 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('churches', '0003_church_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devotional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('scripture_reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='Scripture Reference')),
                ('date', models.DateField(verbose_name='Date')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devotionals', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devotionals', to='churches.church', verbose_name='Church')),
            ],
            options={
                'verbose_name': 'Devotional',
                'verbose_name_plural': 'Devotionals',
                'db_table': 'devotionals',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DevotionalComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('devotional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='devotionals.devotional', verbose_name='Devotional')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devotional_comments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Devotional Comment',
                'verbose_name_plural': 'Devotional Comments',
                'db_table': 'devotional_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DevotionalReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('pray', 'Praying'), ('amen', 'Amen')], max_length=20, verbose_name='Reaction Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('devotional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='devotionals.devotional', verbose_name='Devotional')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devotional_reactions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Devotional Reaction',
                'verbose_name_plural': 'Devotional Reactions',
                'db_table': 'devotional_reactions',
                'unique_together': {('devotional', 'user')},
            },
        ),
    ]
