# Generated by Django 6.0.1 on 2026-02-04 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('churches', '0003_church_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20, verbose_name='Priority')),
                ('category', models.CharField(choices=[('announcement', 'Announcement'), ('event', 'Event'), ('reminder', 'Reminder'), ('urgent', 'Urgent')], default='announcement', max_length=50, verbose_name='Category')),
                ('date', models.DateField(verbose_name='Date')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='churches.church', verbose_name='Church')),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
                'db_table': 'notices',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
