from django.db import models
from common.models import TimeStampedModel
import secrets
import string


class Budget(TimeStampedModel):
    """Budget model"""
    user = models.ForeignKey('accounts.User', on_delete=models.CASCADE, related_name='budgets')
    name = models.CharField(max_length=200)
    department = models.CharField(max_length=100)
    allocated_amount = models.DecimalField(max_digits=15, decimal_places=2)
    spent_amount = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    period = models.CharField(max_length=20, choices=[
        ('monthly', 'Monthly'),
        ('quarterly', 'Quarterly'),
        ('annual', 'Annual')
    ], default='monthly')
    year = models.IntegerField()
    month = models.IntegerField(null=True, blank=True)  # null for annual/quarterly
    
    class Meta:
        db_table = 'budgets'
        verbose_name = 'Budget'
        verbose_name_plural = 'Budgets'
        ordering = ['-year', '-month']
    
    def __str__(self):
        return f"{self.name} - {self.allocated_amount}"
    
    @property
    def remaining_amount(self):
        return self.allocated_amount - self.spent_amount
    
    @property
    def utilization_percentage(self):
        if self.allocated_amount > 0:
            return (self.spent_amount / self.allocated_amount) * 100
        return 0


def _generate_pin(length=6) -> str:
    """Return a secure numeric PIN of the given length."""
    return ''.join(secrets.choice(string.digits) for _ in range(length))


class BudgetAccessPin(models.Model):
    """
    A time-limited PIN generated by the treasurer that lets church members
    view the budget summary from the mobile app without full admin access.
    """
    pin        = models.CharField(max_length=8)
    label      = models.CharField(max_length=200, blank=True,
                                  help_text='Optional description, e.g. "Q2 Budget Review"')
    expires_at = models.DateTimeField()
    is_active  = models.BooleanField(default=True)
    view_count = models.PositiveIntegerField(default=0)
    max_uses   = models.PositiveIntegerField(
        null=True, blank=True,
        help_text='Leave blank for unlimited uses within the time window')
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        'accounts.User', on_delete=models.CASCADE, related_name='budget_pins')
    church     = models.ForeignKey(
        'churches.Church', on_delete=models.CASCADE, related_name='budget_access_pins')

    class Meta:
        db_table = 'budget_access_pins'
        ordering = ['-created_at']
        verbose_name = 'Budget Access PIN'
        verbose_name_plural = 'Budget Access PINs'

    def is_valid(self) -> bool:
        from django.utils import timezone
        if not self.is_active:
            return False
        if timezone.now() > self.expires_at:
            return False
        if self.max_uses is not None and self.view_count >= self.max_uses:
            return False
        return True

    def __str__(self):
        return f"PIN {self.pin} — {self.church} (expires {self.expires_at:%Y-%m-%d %H:%M})"
